services:
  alphabot_agent:
    build: ./alphabot_agent/
    container_name: alphabot_agent
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    cap_add:
      - SYS_RAWIO
    volumes:
      - ./alphabot_agent:/app/alphabot_agent
    env_file: ./env/prosody.env
    environment:
      - XMPP_USERNAME=${AGENT_NAME}
    extra_hosts:
      - "prosody:${PROSODY_IP}"

  calibration_agent:
    build: ./calibration_agent/
    container_name: calibration_agent
    volumes:
      - ./calibration_agent:/app/src
    privileged: true
    env_file: ./env/prosody.env
    environment:
      - XMPP_USERNAME=calibration_agent
    extra_hosts:
      - "prosody:${PROSODY_IP}"

  camera_agent:
    build: ./camera_agent/
    container_name: camera_agent
    volumes:
      - ./camera_agent:/app/src
    privileged: true
    env_file: ./env/prosody.env
    environment:
      - XMPP_USERNAME=camera_agent
    extra_hosts:
      - "prosody:${PROSODY_IP}"

  prosody:
    image: prosody/prosody:latest
    container_name: prosody
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5281:5281"
    volumes:
      - ./prosody/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua:ro
      - ./prosody/certs:/etc/prosody/certs:ro
      - ./prosody/modules:/usr/lib/prosody/modules-extra:ro
    networks:
      xmpp_network:
        ipv4_address: 172.20.0.3

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      xmpp_network:
        ipv4_address: 172.20.0.7

  api:
    image: oven/bun:latest
    container_name: xmpp_api
    depends_on:
      - prosody
      - mosquitto
    working_dir: /app
    volumes:
      - ./prosody/api:/app
    command: /bin/sh -c "bun install && bun run start"
    ports:
      - "3000:3000"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      xmpp_network:
        ipv4_address: 172.20.0.4
    extra_hosts:
      - "prosody:172.20.0.3"
      - "mosquitto:172.20.0.7"
      - "internal-api:172.20.0.6"

  dashboard:
    image: dij0s/expose:latest
    container_name: xmpp_dashboard
    ports:
      - "8888:8888"
    networks:
      xmpp_network:
        ipv4_address: 172.20.0.5

  runner:
    build: ./runner_agent
    container_name: runner_agent
    privileged: true
    volumes:
      - ./runner_agent:/app/src
    env_file: ./env/prosody.env
    environment:
      - XMPP_USERNAME=runner
      - RUNNER_TARGET=${RUNNER_TARGET}
    extra_hosts:
      - "prosody:${PROSODY_IP}"

  gate_handler:
    build: ./mosquitto/client
    container_name: gate_handler
    env_file: ./env/prosody.env
    privileged: true
    volumes:
      - ./mosquitto/client:/app
      - /var/run/dbus:/var/run/dbus
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      - xmpp_network
    extra_hosts:
      - "mosquitto:172.20.0.7"

networks:
  xmpp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
